### ISSUE TITLE
Incompatibility with Python 3.7.0

### ISSUE THREAD

**Issue by palnabarun** [rorodata/roro-client#22]
```bash
➜ roro run echo hello world
Traceback (most recent call last):
  File "/home/nabarun/.local/bin/roro", line 7, in <module>
    from roro.cli import cli
  File "/home/nabarun/.local/lib/python3.7/site-packages/roro/__init__.py", line 4, in <module>
    from .projects import get_current_project, Task
  File "/home/nabarun/.local/lib/python3.7/site-packages/roro/projects.py", line 79
    def deploy(self, async=False):
                         ^
SyntaxError: invalid syntax
```

**Comment by palnabarun** [comment]
It works fine with Python 3.6.6
